### ISSUE TITLE
set-env in github ci script fails

### ISSUE THREAD

**Issue by sjperkins** [ratt-ru/packratt#16]
Due to:

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

@smasoka could you do some investigation and come up with a solution? I encountered this in https://github.com/ratt-ru/packratt/pull/15

**Comment by smasoka** [comment]
pushed a fix on the pr #15

**Comment by sjperkins** [comment]
> pushed a fix on the pr #15

thanks!
