### ISSUE TITLE
pyyaml < 6 requirement too strict

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/packratt#23]
I'm running into issues trying to get pfb-clean and QuartiCal running in the same stimela2 recipe. At least part of the problem stems from the pyyaml requirement [here](https://github.com/ratt-ru/packratt/blob/aae9c681f647b8b9ad6d884258b7c4eceff58edd/setup.py#L18). Is there a good reason for this or can I relax it?

**Comment by sjperkins** [comment]
Packratt's configuration is managed by python poetry technically and the setup.py is auto-generated when poetry builds a wheel.

In fact, setup.py shouldn't even really exist, I added it because poetry didn't support development installs (at that stage).

If you modify the requirement, does packratt play nicely with other packages?

**Comment by sjperkins** [comment]
>At least part of the problem stems from the pyyaml requirement [here](https://github.com/ratt-ru/packratt/blob/aae9c681f647b8b9ad6d884258b7c4eceff58edd/setup.py#L18). Is there a good reason for this or can I relax it?

The strictness is probably due to how Poetry specifies dependencies, rather than due to any specific reason.

**Comment by sjperkins** [comment]
The change to correctly fix this would be to remove

1. Remove `setup.py`
2. Update the pyyaml version in `pyproject.toml`

> In fact, setup.py shouldn't even really exist, I added it because poetry didn't support development installs (at that stage).

This isn't necessary any longer due to https://github.com/python-poetry/poetry/issues/34#issuecomment-1055977321

> Installing a Poetry project in editable mode via pip wasn't possible for a long time, because pip doesn't know how to do this. This have changed with [PEP-660](https://www.python.org/dev/peps/pep-0660/). The neccessary hooks were implemented in Poetry's master branch already for a long time and were now backported to the poetry-core 1.0 branch. pip supports editable installs according to PEP-660 since [21.3](https://pip.pypa.io/en/stable/news/#v21-3).

**Comment by landmanbester** [comment]
It looks like there might be a bit more to it. I get
```
ERROR: Project file:///home/landman/software/packratt has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```
So I guess I need to change ```build-backend = "poetry.masonry.api"``` in the pyproject.toml.  I'm not sure to what though. Any ideas?

**Comment by sjperkins** [comment]
#24 and #25 should resolve this, but your pip needs to be up to date. Please reopen if you run into further issues.

**Comment by landmanbester** [comment]
Thanks @sjperkins
